# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:

  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
        - "80:80"
        - "443:443"
    # монтируем директории, слева директории на хостовой машине, справа - куда они монтируются в контейнере
    volumes:
        - ./containers/nginx/hosts:/etc/nginx/conf.d
        - ./app:/var/www
        - ./logs/nginx:/var/log/nginx
    links:
      - php
    command: /bin/bash -c "nginx -g 'daemon off;'"
    restart: always

  php:
    # путь до докер файла указываем относительно директории в build
    build:
      context: containers/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www:rw
      - ./containers/php/config/php.ini:/usr/local/etc/php/conf.d/999-custom.ini
    restart: always
    environment:
      XDEBUG_CONFIG: remote_host=192.168.32.126 #ip address of host-machine

  # with docker-compose, it tries to preserve volumes between runs; since the user is only created on a new database, you probably need to docker-compose rm -v database to delete the container and associated volume.
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
    links:
      - db

  pgadmin:
    image: chorss/docker-pgadmin4
    volumes:
      - ./data/pgadmin:/data
    ports:
      - "5050:5050"
    links:
      - db
volumes:
  postgres_data: